#!/usr/bin/env bash
set -e

pmset_file="$(plenv-pmset-file 2>/dev/null || true)"

if [ -n "$PLENV_PMSETS" ]; then
  echo $PLENV_PMSETS
elif [ -n "$pmset_file" ]; then
  PLENV_PMSETS="$(< "$pmset_file") $PLENV_PMSETS"
  echo $PLENV_PMSETS
else
  echo "no active pmsets" >&2
  exit 1
fi


